// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://twujjvuvxrxejcubbofb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR3dWpqdnV2eHJ4ZWpjdWJib2ZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyODAxOTQsImV4cCI6MjA2OTg1NjE5NH0.46kEPcqE_VNxOSnHGS9ZDe4nFQ7L1Gta6e-rARdXocA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);